version: '3'
services:
  basic:
    build: ./basic
    ports:
      - "23456:80"
  judge:
    build: ./judge
    ports:
      - "80:80"
    links:
      - "judge_db:database"
  judge_db:
    image: "mysql"
    volumes:
      - ./judge/mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=judge"
  sqli-1:
    build: ./SQLi-1
    ports:
      - "34567:80"
    links:
      - "sqli-1_db:database"
  sqli-1_db:
    image: "mysql"
    environment:
      - "MYSQL_DATABASE=sqli"
volumes:
  judge:
    external: true
