version: '3'
services:
  basic:
    build: ./basic
    ports:
      - "80:80"
  cowsay:
    build: ./cowsay
    ports:
      - "23456:23456"
  ctfd:
    image: ctfd/ctfd
    ports:
      - "8000:8000"
    volumes:
      - .ctfd/data/CTFd/logs:/var/log/CTFd
      - .ctfd/data/CTFd/uploads:/var/uploads
  happy-metaverse-year:
    build: ./happy-metaverse-year
    ports:
      - "8003:80"
  gogoro:
    build: ./gogoro
    ports:
     - "420:420"
  sqli-1:
    build: ./SQLi-1
    ports:
      - "34567:80"
    links:
      - "sqli-1_db:database"
  sqli-1_db:
    image: "mysql"
    environment:
      - "MYSQL_DATABASE=sqli"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      