version: '3'
services:
  basic:
    build: ./basic
    ports:
      - "80:80"
  cowsay:
    build: ./cowsay
    ports:
      - "23456:23456"
  ctfd:
    image: ctfd/ctfd
    ports:
      - "8000:8000"
    volumes:
      - .ctfd/data/CTFd/logs:/var/log/CTFd
      - .ctfd/data/CTFd/uploads:/var/uploads
  happy-metaverse-year:
    build: ./happy-metaverse-year
    ports:
      - "8003:80"
  gogoro:
    build: ./gogoro
    ports:
     - "420:420"
     