version: '3'
services:
  basic:
    build: ./basic
    ports:
      - "80:80"
  ctfd:
    image: ctfd/ctfd
    ports:
      - "8000:8000"
    volumes:
      - .ctfd/data/CTFd/logs:/var/log/CTFd
      - .ctfd/data/CTFd/uploads:/var/uploads
    depends_on:
      - ctfd-db

  sqli-1:
    build: ./SQLi-1
    ports:
      - "34567:80"
    links:
      - "sqli-1_db:database"
  sqli-1_db:
    image: "mysql"
    environment:
      - "MYSQL_DATABASE=sqli"
      