version: '3'
services:
  basic:
    build: ./basic
    ports:
      - "23456:80"
  judge:
    build: ./judge
    ports:
      - "80:80"
    links:
      - "judge_db:database"
  judge_db:
    image: "mariadb"
    environment:
      - "MARIADB_ROOT_PASSWORD=serect"
  sqli-1:
    build: ./SQLi-1
    ports:
      - "34567:80"
    links:
      - "sqli-1_db:database"
  sqli-1_db:
    image: "mariadb"
    environment:
      - "MARIADB_ROOT_PASSWORD=serect"
